// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjJUvFrXCpa6s1tlA23_BaGsRZABFIRNk',
    appId: '1:272886945399:web:0404090f0c7437ccb41872',
    messagingSenderId: '272886945399',
    projectId: 'cs426-76ae2',
    authDomain: 'cs426-76ae2.firebaseapp.com',
    storageBucket: 'cs426-76ae2.appspot.com',
    measurementId: 'G-GHPRGDEXWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5VzkVrKHkb4wwsu-6VrtvyqMBEhId65o',
    appId: '1:272886945399:android:c2a719dc82a10a1fb41872',
    messagingSenderId: '272886945399',
    projectId: 'cs426-76ae2',
    storageBucket: 'cs426-76ae2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6NLGe0zpZ9wZXcN8AvoND0kNrC4nYqtI',
    appId: '1:272886945399:ios:ed21b274b8823cf5b41872',
    messagingSenderId: '272886945399',
    projectId: 'cs426-76ae2',
    storageBucket: 'cs426-76ae2.appspot.com',
    iosClientId: '272886945399-p17asdp1igjvp6b7c1faa9vufn1qu9p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeOrderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6NLGe0zpZ9wZXcN8AvoND0kNrC4nYqtI',
    appId: '1:272886945399:ios:1456cd446aa7f886b41872',
    messagingSenderId: '272886945399',
    projectId: 'cs426-76ae2',
    storageBucket: 'cs426-76ae2.appspot.com',
    iosClientId: '272886945399-qllk5vi53g3o9uorjjs1m91me357qqsu.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeOrderApp.RunnerTests',
  );
}
